/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMockUniswapV3Pool,
  IMockUniswapV3PoolInterface,
} from "../../../contracts/mock/IMockUniswapV3Pool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint160",
        name: "sqrtPriceX96",
        type: "uint160",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMockUniswapV3Pool__factory {
  static readonly abi = _abi;
  static createInterface(): IMockUniswapV3PoolInterface {
    return new utils.Interface(_abi) as IMockUniswapV3PoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMockUniswapV3Pool {
    return new Contract(address, _abi, signerOrProvider) as IMockUniswapV3Pool;
  }
}
