/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IWalletFactoryInterface extends utils.Interface {
  functions: {
    "createNewWallet()": FunctionFragment;
    "getImplement()": FunctionFragment;
    "getWallet(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createNewWallet" | "getImplement" | "getWallet"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createNewWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImplement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWallet",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createNewWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getImplement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWallet", data: BytesLike): Result;

  events: {};
}

export interface IWalletFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWalletFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createNewWallet(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getImplement(overrides?: CallOverrides): Promise<[string]>;

    getWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createNewWallet(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getImplement(overrides?: CallOverrides): Promise<string>;

  getWallet(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createNewWallet(overrides?: CallOverrides): Promise<void>;

    getImplement(overrides?: CallOverrides): Promise<string>;

    getWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createNewWallet(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getImplement(overrides?: CallOverrides): Promise<BigNumber>;

    getWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createNewWallet(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getImplement(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWallet(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
