/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWstETH,
  IWstETHInterface,
} from "../../../../contracts/interfaces/lido/IWstETH";

const _abi = [
  {
    inputs: [],
    name: "stETHPerToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokensPerStEth",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IWstETH__factory {
  static readonly abi = _abi;
  static createInterface(): IWstETHInterface {
    return new utils.Interface(_abi) as IWstETHInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWstETH {
    return new Contract(address, _abi, signerOrProvider) as IWstETH;
  }
}
