/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AAVEV3DeltaRiskNeutralStrategy_old3__factory } from "./AAVEV3DeltaRiskNeutralStrategy_old3__factory";
