/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iOracleSol from "./IOracle.sol";
export * as library from "./library";
export { IAToken__factory } from "./IAToken__factory";
export { IFlashLoanReceiver__factory } from "./IFlashLoanReceiver__factory";
export { IIncentivesController__factory } from "./IIncentivesController__factory";
export { ILendingPool__factory } from "./ILendingPool__factory";
export { ILendingPoolAddressProvider__factory } from "./ILendingPoolAddressProvider__factory";
export { IProtocolDataProvider__factory } from "./IProtocolDataProvider__factory";
export { IVariableDebtToken__factory } from "./IVariableDebtToken__factory";
export { IWMATICGateway__factory } from "./IWMATICGateway__factory";
