/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFlashLoanRecipient } from "./IFlashLoanRecipient";
export type { IProtocolFeesCollector } from "./IProtocolFeesCollector";
export type { MockBalancerVault } from "./MockBalancerVault";
