/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface AAVEV3DeltaRiskNeutralStrategy_old3Interface
  extends utils.Interface {
  functions: {
    "aaveV3Adapter()": FunctionFragment;
    "addLeverage(uint256)": FunctionFragment;
    "balancerAdapter()": FunctionFragment;
    "borrow(uint256)": FunctionFragment;
    "calculatePerformanceFee(address)": FunctionFragment;
    "closePosition()": FunctionFragment;
    "createPosition(uint256,uint256)": FunctionFragment;
    "deposit(uint256)": FunctionFragment;
    "dleverOracle()": FunctionFragment;
    "feeReceiver()": FunctionFragment;
    "getAddLeverageInfo(uint256)": FunctionFragment;
    "getGlobalInfo()": FunctionFragment;
    "getPositionInfo(address)": FunctionFragment;
    "getRemoveLeverageInfo(uint256)": FunctionFragment;
    "performanceFeeRatio()": FunctionFragment;
    "positions(address)": FunctionFragment;
    "removeLeverage(uint256)": FunctionFragment;
    "repay(uint256)": FunctionFragment;
    "uniswapV3Adapter()": FunctionFragment;
    "wETH()": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
    "wstETH()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "aaveV3Adapter"
      | "addLeverage"
      | "balancerAdapter"
      | "borrow"
      | "calculatePerformanceFee"
      | "closePosition"
      | "createPosition"
      | "deposit"
      | "dleverOracle"
      | "feeReceiver"
      | "getAddLeverageInfo"
      | "getGlobalInfo"
      | "getPositionInfo"
      | "getRemoveLeverageInfo"
      | "performanceFeeRatio"
      | "positions"
      | "removeLeverage"
      | "repay"
      | "uniswapV3Adapter"
      | "wETH"
      | "withdraw"
      | "wstETH"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "aaveV3Adapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addLeverage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balancerAdapter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePerformanceFee",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPosition",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "dleverOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddLeverageInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemoveLeverageInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "performanceFeeRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positions",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLeverage",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "uniswapV3Adapter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "wETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "wstETH", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "aaveV3Adapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balancerAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePerformanceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dleverOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAddLeverageInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemoveLeverageInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performanceFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "positions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeLeverage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3Adapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wstETH", data: BytesLike): Result;

  events: {
    "Borrow(address,uint256)": EventFragment;
    "CloseLeverage(address,uint256,uint256,uint256)": EventFragment;
    "CollectFee(address,address,uint256)": EventFragment;
    "Deposit(address,uint256)": EventFragment;
    "IncreaseLeverage(address,uint256,uint256,uint256)": EventFragment;
    "Repay(address,uint256)": EventFragment;
    "Withdraw(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Borrow"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CloseLeverage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CollectFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IncreaseLeverage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Repay"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface BorrowEventObject {
  account: string;
  amount: BigNumber;
}
export type BorrowEvent = TypedEvent<[string, BigNumber], BorrowEventObject>;

export type BorrowEventFilter = TypedEventFilter<BorrowEvent>;

export interface CloseLeverageEventObject {
  account: string;
  flashloanETH: BigNumber;
  withdrawWstETH: BigNumber;
  repayETH: BigNumber;
}
export type CloseLeverageEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  CloseLeverageEventObject
>;

export type CloseLeverageEventFilter = TypedEventFilter<CloseLeverageEvent>;

export interface CollectFeeEventObject {
  token: string;
  account: string;
  amount: BigNumber;
}
export type CollectFeeEvent = TypedEvent<
  [string, string, BigNumber],
  CollectFeeEventObject
>;

export type CollectFeeEventFilter = TypedEventFilter<CollectFeeEvent>;

export interface DepositEventObject {
  account: string;
  amount: BigNumber;
}
export type DepositEvent = TypedEvent<[string, BigNumber], DepositEventObject>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface IncreaseLeverageEventObject {
  account: string;
  flashloanWstETH: BigNumber;
  depositWstETHLev: BigNumber;
  borrowETH: BigNumber;
}
export type IncreaseLeverageEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber],
  IncreaseLeverageEventObject
>;

export type IncreaseLeverageEventFilter =
  TypedEventFilter<IncreaseLeverageEvent>;

export interface RepayEventObject {
  account: string;
  amount: BigNumber;
}
export type RepayEvent = TypedEvent<[string, BigNumber], RepayEventObject>;

export type RepayEventFilter = TypedEventFilter<RepayEvent>;

export interface WithdrawEventObject {
  account: string;
  amount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface AAVEV3DeltaRiskNeutralStrategy_old3 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AAVEV3DeltaRiskNeutralStrategy_old3Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aaveV3Adapter(overrides?: CallOverrides): Promise<[string]>;

    addLeverage(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balancerAdapter(overrides?: CallOverrides): Promise<[string]>;

    borrow(
      borrowETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calculatePerformanceFee(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        performance: BigNumber;
        performanceFee: BigNumber;
      }
    >;

    closePosition(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createPosition(
      depositWstETH: PromiseOrValue<BigNumberish>,
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deposit(
      depositWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    dleverOracle(overrides?: CallOverrides): Promise<[string]>;

    feeReceiver(overrides?: CallOverrides): Promise<[string]>;

    getAddLeverageInfo(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { borrowETH: BigNumber; flashLoanFee: BigNumber }
    >;

    getGlobalInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { supplyRate: BigNumber; borrowRate: BigNumber }
    >;

    getPositionInfo(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        totalCollateralBase: BigNumber;
        totalCollateralAmount: BigNumber;
        totalDebtBase: BigNumber;
        totalDebtAmount: BigNumber;
        availableBorrowsBase: BigNumber;
        currentLiquidationThreshold: BigNumber;
        ltv: BigNumber;
        healthFactor: BigNumber;
      }
    >;

    getRemoveLeverageInfo(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        flashLoanETH: BigNumber;
        flashLoanFee: BigNumber;
      }
    >;

    performanceFeeRatio(overrides?: CallOverrides): Promise<[BigNumber]>;

    positions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        collateralETHValue: BigNumber;
        loanETHValue: BigNumber;
        isNotFirst: boolean;
      }
    >;

    removeLeverage(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    repay(
      repayETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    uniswapV3Adapter(overrides?: CallOverrides): Promise<[string]>;

    wETH(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      withdrawWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    wstETH(overrides?: CallOverrides): Promise<[string]>;
  };

  aaveV3Adapter(overrides?: CallOverrides): Promise<string>;

  addLeverage(
    addLeverageWstETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balancerAdapter(overrides?: CallOverrides): Promise<string>;

  borrow(
    borrowETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calculatePerformanceFee(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      performance: BigNumber;
      performanceFee: BigNumber;
    }
  >;

  closePosition(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createPosition(
    depositWstETH: PromiseOrValue<BigNumberish>,
    addLeverageWstETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deposit(
    depositWstETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  dleverOracle(overrides?: CallOverrides): Promise<string>;

  feeReceiver(overrides?: CallOverrides): Promise<string>;

  getAddLeverageInfo(
    addLeverageWstETH: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { borrowETH: BigNumber; flashLoanFee: BigNumber }
  >;

  getGlobalInfo(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { supplyRate: BigNumber; borrowRate: BigNumber }
  >;

  getPositionInfo(
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      totalCollateralBase: BigNumber;
      totalCollateralAmount: BigNumber;
      totalDebtBase: BigNumber;
      totalDebtAmount: BigNumber;
      availableBorrowsBase: BigNumber;
      currentLiquidationThreshold: BigNumber;
      ltv: BigNumber;
      healthFactor: BigNumber;
    }
  >;

  getRemoveLeverageInfo(
    removeLeverageWstETH: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      flashLoanETH: BigNumber;
      flashLoanFee: BigNumber;
    }
  >;

  performanceFeeRatio(overrides?: CallOverrides): Promise<BigNumber>;

  positions(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, boolean] & {
      collateralETHValue: BigNumber;
      loanETHValue: BigNumber;
      isNotFirst: boolean;
    }
  >;

  removeLeverage(
    removeLeverageWstETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  repay(
    repayETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  uniswapV3Adapter(overrides?: CallOverrides): Promise<string>;

  wETH(overrides?: CallOverrides): Promise<string>;

  withdraw(
    withdrawWstETH: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  wstETH(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    aaveV3Adapter(overrides?: CallOverrides): Promise<string>;

    addLeverage(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    balancerAdapter(overrides?: CallOverrides): Promise<string>;

    borrow(
      borrowETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    calculatePerformanceFee(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        performance: BigNumber;
        performanceFee: BigNumber;
      }
    >;

    closePosition(overrides?: CallOverrides): Promise<void>;

    createPosition(
      depositWstETH: PromiseOrValue<BigNumberish>,
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    deposit(
      depositWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    dleverOracle(overrides?: CallOverrides): Promise<string>;

    feeReceiver(overrides?: CallOverrides): Promise<string>;

    getAddLeverageInfo(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { borrowETH: BigNumber; flashLoanFee: BigNumber }
    >;

    getGlobalInfo(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { supplyRate: BigNumber; borrowRate: BigNumber }
    >;

    getPositionInfo(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        totalCollateralBase: BigNumber;
        totalCollateralAmount: BigNumber;
        totalDebtBase: BigNumber;
        totalDebtAmount: BigNumber;
        availableBorrowsBase: BigNumber;
        currentLiquidationThreshold: BigNumber;
        ltv: BigNumber;
        healthFactor: BigNumber;
      }
    >;

    getRemoveLeverageInfo(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        flashLoanETH: BigNumber;
        flashLoanFee: BigNumber;
      }
    >;

    performanceFeeRatio(overrides?: CallOverrides): Promise<BigNumber>;

    positions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, boolean] & {
        collateralETHValue: BigNumber;
        loanETHValue: BigNumber;
        isNotFirst: boolean;
      }
    >;

    removeLeverage(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    repay(
      repayETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    uniswapV3Adapter(overrides?: CallOverrides): Promise<string>;

    wETH(overrides?: CallOverrides): Promise<string>;

    withdraw(
      withdrawWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    wstETH(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Borrow(address,uint256)"(account?: null, amount?: null): BorrowEventFilter;
    Borrow(account?: null, amount?: null): BorrowEventFilter;

    "CloseLeverage(address,uint256,uint256,uint256)"(
      account?: null,
      flashloanETH?: null,
      withdrawWstETH?: null,
      repayETH?: null
    ): CloseLeverageEventFilter;
    CloseLeverage(
      account?: null,
      flashloanETH?: null,
      withdrawWstETH?: null,
      repayETH?: null
    ): CloseLeverageEventFilter;

    "CollectFee(address,address,uint256)"(
      token?: null,
      account?: null,
      amount?: null
    ): CollectFeeEventFilter;
    CollectFee(
      token?: null,
      account?: null,
      amount?: null
    ): CollectFeeEventFilter;

    "Deposit(address,uint256)"(
      account?: null,
      amount?: null
    ): DepositEventFilter;
    Deposit(account?: null, amount?: null): DepositEventFilter;

    "IncreaseLeverage(address,uint256,uint256,uint256)"(
      account?: null,
      flashloanWstETH?: null,
      depositWstETHLev?: null,
      borrowETH?: null
    ): IncreaseLeverageEventFilter;
    IncreaseLeverage(
      account?: null,
      flashloanWstETH?: null,
      depositWstETHLev?: null,
      borrowETH?: null
    ): IncreaseLeverageEventFilter;

    "Repay(address,uint256)"(account?: null, amount?: null): RepayEventFilter;
    Repay(account?: null, amount?: null): RepayEventFilter;

    "Withdraw(address,uint256)"(
      account?: null,
      amount?: null
    ): WithdrawEventFilter;
    Withdraw(account?: null, amount?: null): WithdrawEventFilter;
  };

  estimateGas: {
    aaveV3Adapter(overrides?: CallOverrides): Promise<BigNumber>;

    addLeverage(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balancerAdapter(overrides?: CallOverrides): Promise<BigNumber>;

    borrow(
      borrowETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calculatePerformanceFee(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    closePosition(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createPosition(
      depositWstETH: PromiseOrValue<BigNumberish>,
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deposit(
      depositWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    dleverOracle(overrides?: CallOverrides): Promise<BigNumber>;

    feeReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    getAddLeverageInfo(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGlobalInfo(overrides?: CallOverrides): Promise<BigNumber>;

    getPositionInfo(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRemoveLeverageInfo(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    performanceFeeRatio(overrides?: CallOverrides): Promise<BigNumber>;

    positions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeLeverage(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    repay(
      repayETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    uniswapV3Adapter(overrides?: CallOverrides): Promise<BigNumber>;

    wETH(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      withdrawWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    wstETH(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    aaveV3Adapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addLeverage(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balancerAdapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrow(
      borrowETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calculatePerformanceFee(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    closePosition(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createPosition(
      depositWstETH: PromiseOrValue<BigNumberish>,
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      depositWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    dleverOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeReceiver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAddLeverageInfo(
      addLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGlobalInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPositionInfo(
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRemoveLeverageInfo(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    performanceFeeRatio(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    positions(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeLeverage(
      removeLeverageWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    repay(
      repayETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    uniswapV3Adapter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    wETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      withdrawWstETH: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    wstETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
