/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IDLeverOracle,
  IDLeverOracleInterface,
} from "../../../contracts/interfaces/IDLeverOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDLeverOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IDLeverOracleInterface {
    return new utils.Interface(_abi) as IDLeverOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDLeverOracle {
    return new Contract(address, _abi, signerOrProvider) as IDLeverOracle;
  }
}
