/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILeverStrategy,
  ILeverStrategyInterface,
} from "../../../contracts/interfaces/ILeverStrategy";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "addLeverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "AddLeverage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "borrowAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "Borrow",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "ClosePosition",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "principalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "leverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "CreatePosition",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "addLeverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "DepositAndAddLeverage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "depositAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "removeLeverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "DepositAndRemoveLeverage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "removeLeverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "RemoveLeverage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "repayAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "Repay",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "withdrawAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "withdrawAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "addLeverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "WithdrawAndAddLeverage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "withdrawAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "removeLeverageAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "lastPositionNetValue",
        type: "uint256",
      },
    ],
    name: "WithdrawAndRemoveLeverage",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "addLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "addLeverage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "borrowETH",
        type: "uint256",
      },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "calculatePositionStatus",
    outputs: [
      {
        internalType: "uint256",
        name: "performance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "performanceFee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lastPostionNetValue",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "closePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "depositWstETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "addLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "createPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "depositWstETH",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "depositWstETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "addLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "depositAndAddLeverage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "depositWstETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "removeLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "depositAndRemoveLeverage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "earnToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGlobalInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "supplyRate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "borrowRate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getPositionInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "totalCollateralBase",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalCollateralAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDebtBase",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalDebtAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "availableBorrowsBase",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentLiquidationThreshold",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "ltv",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "healthFactor",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "removeLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "removeLeverage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "repayETH",
        type: "uint256",
      },
    ],
    name: "repay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "withdrawWstETH",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "withdrawWstETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "addLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "withdrawAndAddLeverage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "withdrawWstETH",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "removeLeverageWstETH",
        type: "uint256",
      },
    ],
    name: "withdrawAndRemoveLeverage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILeverStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): ILeverStrategyInterface {
    return new utils.Interface(_abi) as ILeverStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILeverStrategy {
    return new Contract(address, _abi, signerOrProvider) as ILeverStrategy;
  }
}
