/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPCToken__factory } from "./IPCToken__factory";
export { IPolyCoachFactory__factory } from "./IPolyCoachFactory__factory";
export { IPolyCoachIncentive__factory } from "./IPolyCoachIncentive__factory";
